### ISSUE TITLE
Metzmatan's Mark rules?

### ISSUE THREAD

**Issue by sirkerry** [Mxblah/metzmatan#3]
Are the rules for the Metzmatan's Mark RPG available anywhere online?

**Comment by Mxblah** [comment]
Hi; thanks for your interest in this (very much still in-development) system! The test rulebook is available in pdf form on the releases page of this Git repo: https://github.com/Mxblah/metzmatan/releases/tag/v0.1.1 ([direct link](https://github.com/Mxblah/metzmatan/releases/download/v0.1.1/MzMa.Test.Rulebook.v0.1.1.pdf))

I do intend to update the release process to include the pdf in a more obvious way for future releases.
